routes/web.php
<?php

use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\GenreController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GenreController::class, 'index'])->name('home');
Route::resource('books', BookController::class);
Route::resource('genres', GenreController::class);
Route::resource('authors', AuthorController::class);
Route::get('/users/register', [App\Http\Controllers\UsersController::class, 'register'])->name('users.register');
Route::post('/users', [App\Http\Controllers\UsersController::class, 'store'])->name('users.store');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Genre extends Model
{
    use HasFactory;

    protected $fillable = ['genre'];

    /**
     * @return HasMany
     */
    public function books(): HasMany
    {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GenreRequest;
use App\Models\Book;
use App\Models\Genre;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $genres = Genre::all();
        return view('genres.index', compact('genres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        return view('genres.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param GenreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(GenreRequest $request): RedirectResponse
    {
        $genre = new Genre();
        $genre->genre = $request->input('genre');
        $genre->save();
        return redirect()->route('genres.index')->with('status', "Genre: {$genre->genre} successfully created!");
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Genre $genre
     * @return Application|Factory|View|Response
     */
    public function show(Genre $genre)
    {
        $genre->setRelation('books', $genre->books()->simplePaginate(9));

        return view('genres.show', compact('genre'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Genre $genre
     * @return Application|Factory|View|Response
     */
    public function edit(Genre $genre)
    {
        return view('genres.edit', compact('genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Genre $genre
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(GenreRequest $request, Genre $genre): RedirectResponse
    {
        $genre->genre = $request->input('genre');
        $genre->save();
        return redirect()->route('genres.index')->with('status', "Genre: {$genre->genre} successfully updated!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Genre $genre
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Genre $genre)
    {
        $genre->delete();
        return redirect()->route('genres.index')->with('status', "Genre: {$genre->genre} successfully deleted");
    }
}

resources/views/genres/index.blade.php
@extends('layouts.app')
 @section('content')
     <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
         <h3 class="w3-bar-item">Menu</h3>
         <a href="{{route('books.index')}}">all</a>
         @foreach($genres as $genre)
             <a href="{{route('genres.show', ['genre' => $genre])}}">{{$genre->genre}}</a>
         @endforeach
     </div>
 @endsection

resources/views/genres/show.blade.php
@extends('layouts.app')
@section('content')
    <div style="margin-left:25%">
       <div class="d-flex align-items-center mt-4">
        <div class="flex-grow-1 ms-3">
            <h3>Книги жанра {{$genre->genre}}</h3>
        </div>
    </div>
    </div>
    <div class="row row-cols-md-3 g-4">
    @foreach($genre->books as $book)

            <div class="col" style="margin-bottom: 10px">
                <div class="card h-100">
                    @if($book->picture)
                        <img src="{{asset('/storage/' .$book->picture)}}" class="card-img-top" alt="{{$book->picture}}" width="100" height="400">
                    @else
                        <img src="{{asset('/storage/pictures/img.png')}}" class="card-img-top" alt="..." width="200" height="300">
                    @endif
                    <div class="card-body">
                        <a href="{{route('books.show', ['book' => $book])}}" ><h5 class="card-title">{{$book->name}}</h5></a>
                        <h5 class="card-title">{{$book->title}}</h5>
                        <p class="card-text">{{is_null($book->genre) ? "No genre": $book->genre->genre}}</p>
                        <p class="card-text">Автор:{{is_null($book->author) ? "No author": $book->author->author}}</p>
                        <a href="{{route('books.show',['book' => $book])}}">Подробнее...</a>
                    </div>
                </div>
            </div>

    @endforeach
    </div>
    <div class="row">
        <div class="vol-md-auto">
                {{$genre->books->links()}}
        </div>
    </div>
@endsection